### PR TITLE
Prevent conflicts when using multiple MiniJooms on the same page

### PR DESCRIPTION
**Pull request by Chraneco**
Fixes https://github.com/JoomGallery/JoomGallery/issues/75

### CODE REVIEW

**Comment by MrMusic** [comment]
Yes, after this change inserting the image works again.
Now, however, a error appears when selecting a thumbnail as category thumbnail: 'TypeError: form is null'

**Comment by Chraneco** [comment]
This is probably fixed with the current version of JoomGallery on GitHub. Could you please go to the `master` branch of the JoomGallery repository and click the "Download ZIP button. After installing that version it should work.

**Comment by MrMusic** [comment]
I tried it two times again after reinstalling the actual master branch and delete the browser-cache: Unfortunately, the error still occurs: After inserting an image into the category description it is no longer possible to change the category thumbnail.  :confused:
Tested with Firefox and Edge. Error in mini.js, line 39.

**Comment by Erftralle** [comment]
> After inserting an image into the category description it is no longer possible to change the category thumbnail.

I can confirm that.
I think we could cope with that problem by adding `&prefix=joom` to the request URL to open the MiniJoom in the thumbnail form field (https://github.com/JoomGallery/JoomGallery/blob/master/administrator/components/com_joomgallery/models/fields/thumbnail.php#L115).

**Comment by Chraneco** [comment]
Thanks, I can confirm that adding this prefix for the category thumbnail selection fixes this problem and I checked it in to `master`.
For a more robust solution we may want to add some kind of ID in the future for each MiniJoom instance and store separate session values for each ID. Right now values are just overridden with every instance that is opened.

**Comment by Erftralle** [comment]
> For a more robust solution we may want to add some kind of ID in the future for each MiniJoom instance and store separate session values for each ID. Right now values are just overridden with every instance that is opened.

Sounds like a good idea.

**Pull request merged**
